### ISSUE TITLE
Font Error

### ISSUE THREAD

**Issue by jellycsc** [Gaohaoyang/gaohaoyang.github.io#100]
Access to Font at 'https://cdn.bootcss.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0' from origin 'https://gaohaoyang.github.io' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://pay.skyrich.net' that is not equal to the supplied origin. Origin 'https://gaohaoyang.github.io' is therefore not allowed access.

**Comment by sigusr1** [comment]
I meet the same problem

**Comment by jellycsc** [comment]
Resolved.
