### ISSUE TITLE
iPhone手机打不开评论

### ISSUE THREAD

**Issue by kylescript** [Gaohaoyang/gaohaoyang.github.io#103]
iPhone手机打不开评论系统。
查了一下是原因是iPhone无法访问：https://gaohaoyang.disqus.com/embed.js
有人知道是为什么吗？  可以直接把这个连接在手机微信或者浏览器中打开试试，发现访问不了。PC浏览器却是好的，为什么呢？

**Comment by TangMingliang95** [comment]
Disqus 是国内不能直连的网站，你的电脑在网络连接方面做了特殊处理，而手机没有。

**Comment by kylescript** [comment]
@TangMingliang95 原来如此，我电脑一直挂着ss的，竟然忘了这茬了。。。多谢！
