### ISSUE TITLE
博文中多点几次代码块，footer会飘到中间去

### ISSUE THREAD

**Issue by QigangZhong** [Gaohaoyang/gaohaoyang.github.io#116]
例如这篇文章：
https://gaohaoyang.github.io/2018/09/10/lottie/#%E4%BD%BF%E7%94%A8

多点几次下面的js代码块中的代码，然后页面拉到最下面，会发现footer不见了，飘到中间去了，只要有代码块，点几次，问题必现，浩阳兄有注意到么？

**Comment by Saltwind** [comment]
> 例如这篇文章：
> https://gaohaoyang.github.io/2018/09/10/lottie/#%E4%BD%BF%E7%94%A8
> 
> 多点几次下面的js代码块中的代码，然后页面拉到最下面，会发现footer不见了，飘到中间去了，只要有代码块，点几次，问题必现，浩阳兄有注意到么？

我猜你是开了有道翻译插件？只要双击选中一个英文单词，footer就飘上去了

**Comment by newblueskylinux** [comment]
发现一个问题，我用你的代码建的网站http://newbluesky.top，博文开始用的你的原文文件改名并且改的内容改成我自己的，在首页显示缩略内容的时候你在md文件中用的是五行空行隔开的是吧？
我自己在windows上新建的文本文件改成md后缀，并且同样内容用notepad++打开复制进去，网站首页显示的是全部，不是缩略内容。Linux上新建的文件一样无法显示缩略（会显示md文件的全部内容）
然后又用你的源文件改的又可以显示缩略，不知道为什么？浩阳大哥看到的话给个回复

**Comment by newblueskylinux** [comment]
你的其它代码我都没动，感觉完全就出在md文件的来源问题上，同样内容的文件，跟Windows-style (CRLF)有关吗

**Comment by QigangZhong** [comment]
> > 例如这篇文章：
> > https://gaohaoyang.github.io/2018/09/10/lottie/#%E4%BD%BF%E7%94%A8
> > 多点几次下面的js代码块中的代码，然后页面拉到最下面，会发现footer不见了，飘到中间去了，只要有代码块，点几次，问题必现，浩阳兄有注意到么？
> 
> 我猜你是开了有道翻译插件？只要双击选中一个英文单词，footer就飘上去了

果然是有道词典插件引起的问题，谢了~

**Comment by QigangZhong** [comment]
有道词典浏览器插件引起的问题
