### ISSUE TITLE
C++代码块支持问题

### ISSUE THREAD

**Issue by ccpocker** [Gaohaoyang/gaohaoyang.github.io#120]
使用C++代码块:
无法正常实现代码高亮之类。
问题如下
![selection_002](https://user-images.githubusercontent.com/24786402/49066028-d2a7f080-f25a-11e8-80c2-c3326bb8ce3c.png)

**Comment by TangMingliang95** [comment]
使用 \`\`\`cpp 而不是 \`\`\`c++
