### ISSUE TITLE
gitalk gitment support

### ISSUE THREAD

**Issue by suliveevil** [Gaohaoyang/gaohaoyang.github.io#122]
请问可以加入对gitalk或者gitment的支持吗？
我试了按gitalk主页的做法将代码写到layouts/page.html里，但是影响到content的显示（无法跟随页面移动）。

**Comment by NicolasLee** [comment]
gittalk评论寻找中，希望老铁可以添加支持。

**Comment by Gaohaoyang** [comment]
考虑近期支持

**Comment by sxgpyjg** [comment]
我已添加gitalk评论https://github.com/sxgpyjg/sxgpyjg.github.io效果地址

**Comment by sxgpyjg** [comment]
这个评论也不错https://github.com/sxgpyjg/sxgpyjg.github.io

**Comment by changwh** [comment]
实现了gitment的调用
可参考https://changwh.github.io/2019/04/05/change-comment-tool/

**Comment by Qin-Dong** [comment]
我的已自己添加gitalk评论
[http://qin-dong.github.io](http://qin-dong.github.io)
代码请前往仓库自行查看。

**Comment by suliveevil** [comment]
感谢感谢
