### ISSUE TITLE
加了一个简单目录

### ISSUE THREAD

**Issue by javakam** [Gaohaoyang/gaohaoyang.github.io#136]
改动很小,仅需post.html 简单编辑即可👉 [https://github.com/javakam/javakam.github.io/blob/master/_layouts/post.html](https://github.com/javakam/javakam.github.io/blob/master/_layouts/post.html)

效果预览 👉 [https://javakam.github.io/2019/10/21/PHP-11.MySQL扩展/](https://javakam.github.io/2019/10/21/PHP-11.MySQL扩展/)

**Comment by Gaohaoyang** [comment]
Thanks, however there was a content already. Just use 

```
* content
{:toc}
```

at the first of the article(after the `---` meta info)
