### ISSUE TITLE
改进的一些建议

### ISSUE THREAD

**Issue by zhiyingfang** [Gaohaoyang/gaohaoyang.github.io#15]
我目前的网站正在使用你的主题，先谢谢你，因为我对代码完全小白，在搜了一些方法之后还是不能进行很好的改进，正好看到你说准备改版，所以提一些我的建议，如果能有时间更新最好，再次感谢。
1.希望能加一个适应主题的站内搜索，因为右上角可以添加新的栏目，再加搜索不大方便，所以建议和TOP键一起做成一个悬浮的搜索。
2.原有的TOP有点过大了，感觉和主题不大符合，建议改成和主题相符的图标。
再次感谢！

**Comment by Gaohaoyang** [comment]
好的，谢谢你给的建议。我4月1日，研究生毕业预答辩，这两天确实忙。答辩后，改版。

实际上已经在慢慢改版了，在这个仓库 https://github.com/Gaohaoyang/blog-based-on-jekyll-3

**Comment by Gaohaoyang** [comment]
博客主题已更新，请看README

回到顶部还没完成，正在制作。

**Comment by brianway** [comment]
正想说回到顶部的功能咋没了。


另外评论部分感觉可以抽取出来放到"_includes/comments.html"下，其他页面要用评论时是需要`	   {% include comments.html %}`就行了，我已经做了这部分工作:[_includes/comments.html](https://github.com/brianway/brianway.github.io/blob/master/_includes/comments.html)

**Comment by Gaohaoyang** [comment]
嗯，对应该把公共代码提取出来

**Comment by Gaohaoyang** [comment]
回到顶部已经完成。
