### ISSUE TITLE
关于移动端导航栏的问题

### ISSUE THREAD

**Issue by xb9207** [Gaohaoyang/gaohaoyang.github.io#20]
我用chrome浏览器切换成移动端显示的时候：

第一次切换过去的时候点击导航按钮，是无效的，

当我点击你的“HYG”回到主页后再点击导航按钮就有效果了。

**Comment by Gaohaoyang** [comment]
是的，如果不手动刷新的话，确实是无效的。

我在考虑用户应该不会再使用的时候突然把浏览器宽度调小吧。

可能只有一种情况，在移动设备上，旋转屏幕后，如果不手动刷新的话，会出现按钮无效，嗯，我考虑一下怎么修改这个问题。

**Comment by xb9207** [comment]
嗯...确实是这样，一般情况下不会这样。。
