### ISSUE TITLE
标签页中标签div长度太长导致超出页面范围

### ISSUE THREAD

**Issue by xb9207** [Gaohaoyang/gaohaoyang.github.io#21]
屏幕小的时候标签页中标签div长度太长导致超出页面范围：

![](http://i.imgur.com/iDXYNbk.png)

或是这样：

![](http://i.imgur.com/q4MHfGJ.png)

感觉有点不美观。。可否令它移动一定范围就不移动？或是设置个最大高度？

**Comment by Gaohaoyang** [comment]
嗯，这是个问题，我也发现了，准备修复。

**Comment by Gaohaoyang** [comment]
已修复
