### ISSUE TITLE
uc浏览器（android）点击导航菜单和内容锚点没有反应

### ISSUE THREAD

**Issue by mahuafactory** [Gaohaoyang/gaohaoyang.github.io#22]
在android版本的uc浏览器上，点击右上角的导航菜单几次之后，就不再弹出了。

其次，在点击任何一篇文章里面的内容锚点，不会进行跳转，pc上没有问题

**Comment by Gaohaoyang** [comment]
> 在android版本的uc浏览器上，点击右上角的导航菜单几次之后，就不再弹出了。

这个我再研究研究。

> 其次，在点击任何一篇文章里面的内容锚点，不会进行跳转，pc上没有问题

这个问题，我在Android微信内置浏览器上也发现了，我有空再看看是什么问题。

**Comment by Gaohaoyang** [comment]
#48

**Comment by Gaohaoyang** [comment]
fixed
