### ISSUE TITLE
当_post目录下的文件个数小于3时，出现这个错误Regenerating: 1 file(s) changed at 2016-05-05 16:14:31   Liquid Exception:divided by 0 in index.html

### ISSUE THREAD

**Issue by robotlife** [Gaohaoyang/gaohaoyang.github.io#26]

**Comment by Gaohaoyang** [comment]
是的，我也发现了这个错误。这是因为主页上标签云代码的问题，导致除数为零了。

关于标签云部分的代码，我有空再仔细看看，这部分使用了别人写好的现成代码。

应该是`index.html`中122和123行的问题，如下：

```
{% assign temp = tag[1].size | minus: min | times: 36 | divided_by: diff %}
{% assign base = temp | divided_by: 4 %}
```

**Comment by Gaohaoyang** [comment]
>  如何修改首页的Categories和Tags？

上一个问题，嗯再`page`文件夹下可以进行修改。

若不需要这两个页面，直接把`1category.html`和`2tags.html`中的`title`删掉即可

**Comment by leocook** [comment]
我观察了一下，只要标签的个数不是大于或者等于２个，就不会出现divided by 0这个问题。

**Comment by iver3on** [comment]
标签的个数大于3 或者页面数目大于3 这个问题照样出现是什么鬼。。

**Comment by iver3on** [comment]
找到蛋疼的问题了。。我提交的文章都是当天，比如说5.10号，文章无效，这个导致文章数目不满足或者标签数目不满足出错。
查了下：
由于jekyll 3（github目前的jekyll版本）默认对于认定为"未来"的post，是不生成的，详情可以参考Future posts - Jekyll。我把所有文件改成5.9号就可以了。
具体问题好像在feed.xml里面，具体没有研究。。真是蛋疼。

**Comment by pysense** [comment]
我也碰到这个问题了，跟楼上的情况都不同。只有两种情况可以通过，一是不设置 tags，二是设置的 tags 只有1个且是个数字（比如设置为 12345 可以，设置为 hi 就不行）

**Comment by jiangzhengshen** [comment]
我想应该是这个原因：所有post里面设置的tag均只出现了一次，而标签云是根据tag的频率显示的，所有tag的频率相同时，会出现这个问题。

index.html里面第119行
```javascript
{% assign diff = max | minus: min %}
```
应该是 diff=max-min 的意思，如果所有tag的频率相同，那么 diff=0

这就导致第122行
```javascript
{% assign temp = tag[1].size | minus: min | times: 36 | divided_by: diff %}
```
出现了除0错误。

**Comment by xiaomenglnan** [comment]
遇到了这个错误，博主很迅速的给了回复，按照博主的建议多加了几个页面，博客可以正常访问。代码应该看不懂，我就不看了，先用起来，慢慢研究。

**Comment by Gaohaoyang** [comment]
我添加了几行代码，修复了这个bug

见https://github.com/Gaohaoyang/gaohaoyang.github.io/commit/d130f07828cbaa13ec7528fd065ecd3c92409b4b

**Comment by Gaohaoyang** [comment]
感谢 @jiangzhengshen 准确地指出bug所在！

**Comment by xiaomenglnan** [comment]
你好，我还想请问一下，这里面写的文章可以设置是否公开之类的么？

在 2016-06-13 16:07:38，"浩阳" <notifications@github.com> 写道：


感谢 @jiangzhengshen 准确地指出bug所在！

**Comment by Gaohaoyang** [comment]
可以使用草稿，drafts。

参见jekyll官方文档 https://jekyllrb.com/docs/drafts/

**Comment by xiaomenglnan** [comment]
多谢，我试一下~

在 2016-06-13 19:57:24，"浩阳" <notifications@github.com> 写道：


可以使用草稿，drafts。

参见jekyll官方文档 https://jekyllrb.com/docs/drafts/
