### ISSUE TITLE
点击Content下面的toc,页面不会跳转

### ISSUE THREAD

**Issue by leocook** [Gaohaoyang/gaohaoyang.github.io#27]
ＲＴ，点击Content下面的toc,页面不会跳转。请问博主，这块是故意这样设置的吗？如何才能点击后可以实现跳转呢？谢谢！

**Comment by Gaohaoyang** [comment]
我没有看懂你的问题描述，你是说右侧Content下面的ul列表吗？

应该是可以进行锚点跳转的。我测试没有问题。

这个ul列表的内容是来自正文区的标题。kramdown的markdown里面的语法是使用这两行代码：

```
* content
{:toc}
```

在正文的这里形成一个ul列表，我将它隐藏，并转移到了右侧的Content区域。

**Comment by leocook** [comment]
是我的浏览器问题，ubuntu14.04下的chrome，无法跳转，但是火狐就可以。谢谢！

发自我的 iPhone

**Comment by wenfh2020** [comment]
> 我没有看懂你的问题描述，你是说右侧Content下面的ul列表吗？
> 
> 应该是可以进行锚点跳转的。我测试没有问题。
> 
> 这个ul列表的内容是来自正文区的标题。kramdown（markdown解析引擎）的markdown里面的语法是使用这两行代码：
> 
> ```
> * content
> {:toc}
> ```
> 
> 在正文的这里形成一个ul列表，我将它隐藏，并转移到了右侧的Content区域。

恰巧，我不喜欢博客右侧区域，通过这个 issures 重新打开了正文的 toc 跳转。感谢博主的框架，我基于这个框架，也做了不少 DIY。(wenfh2020.com)
