### ISSUE TITLE
push目录_posts时Page build failed

### ISSUE THREAD

**Issue by xiaodongQ** [Gaohaoyang/gaohaoyang.github.io#28]
你好，很喜欢你这个博客风格，对于前端不大熟悉，根据你的模板创建博客时遇到个问题，试了很久没解决。

> 在_posts添加文章，push后提示页面构建失败。(master分支下)

_请问：_

1. 该博客中本地是否必须安装jekyll，来生成相关文件(_site?)

2. 我遇到的问题是否是分支造成，能否添加本地需要的操作和分支相关的说明。试过：[github 不支持 jekyll 插件的解决方法](http://www.chinaxing.org/articles/linux/2012/12/05/2012-12-05-github-do-not-support-jekyll-plugin.html)

**Comment by Gaohaoyang** [comment]
> * 该博客中本地是否必须安装jekyll，来生成相关文件(_site?)

不需要。详情自行搜索 github pages。

>  * 我遇到的问题是否是分支造成，能否添加本地需要的操作和分支相关的说明。试过：github 不支持 jekyll 插件的解决方法

我认为不是分支的原因。同时这个博客主题只用到了分页插件，但 github 是支持这个插件的。原本分页功能就是集成在 jekyll 里面的，只是在 jekyll3.0.0+ 的时候分离出来了而已。详情参考 https://jekyllrb.com/docs/pagination/

你 Page build failed 有可能是标签云的问题，详情看这个 https://github.com/Gaohaoyang/gaohaoyang.github.io/issues/26

**Comment by xiaodongQ** [comment]
是的，是标签的问题，本地jekyll之前有问题一直测不了，重装了一下。3Q~
