### ISSUE TITLE
如何添加分页？

### ISSUE THREAD

**Issue by studiotang** [Gaohaoyang/gaohaoyang.github.io#3]
您好！
       您的博客主题非常漂亮，我fork了一份代码，并且按您博客的步骤做完，博客可以正常显示。
       但是，发现首页无法实现分页，本人对前端不太了解，想请问一下作者如何解决这个问题？

**Comment by Gaohaoyang** [comment]
分页是 jekyll 语法提供的。http://jekyllcn.com/docs/pagination/ 详情见这里

**Comment by studiotang** [comment]
感谢博主，问题已解决。

**Comment by cqustone** [comment]
_config.yml   添加代码gems: [jekyll-paginate]即可
刚开始用git，提交了pull request，不知道正确不正确
感谢您的博客主题
