### ISSUE TITLE
使用中的一些问题

### ISSUE THREAD

**Issue by xiaomenglnan** [Gaohaoyang/gaohaoyang.github.io#30]
你好，我想问下怎么能把博客模板中的内容删掉呢？我把posts中的md文件删掉之后，访问自己的网站名称还是会显示所有模板中的博文。

**Comment by Gaohaoyang** [comment]
是这样的，我看了你的页面，应该是构建失败了。不是你的原因，是我在制作模板的时候忽略了只有一篇文章时对于tags的计数方式。简单的说就是首页标签云那部分代码出错了，导致jekyll 构建失败。

解决办法：你暂时先多放几篇文章吧，让标签出现的频率不相同。详情见https://github.com/Gaohaoyang/gaohaoyang.github.io/issues/26

**Comment by Gaohaoyang** [comment]
现在你的博客能访问是因为使用了构建失败前成功的那一次构建。

**Comment by xiaomenglnan** [comment]
我写了三篇还是不行，估计还需要再写几篇，试一下。

在 2016-06-13 15:10:51，"浩阳" <notifications@github.com> 写道：


是这样的，我看了你的页面，应该是构建失败了。不是你的原因，是我在制作模板的时候忽略了只有一篇文章时对于tags的计数方式。简单的说就是首页标签云那部分代码出错了，导致jekyll 构建失败。

解决办法：你暂时先多放几篇文章吧，让标签出现的频率不相同。详情见#26

**Comment by Gaohaoyang** [comment]
我添加了几行代码，修复了这个bug

见https://github.com/Gaohaoyang/gaohaoyang.github.io/commit/d130f07828cbaa13ec7528fd065ecd3c92409b4b
