### ISSUE TITLE
能否增加对色彩主题的可配置

### ISSUE THREAD

**Issue by waruqi** [Gaohaoyang/gaohaoyang.github.io#33]
很喜欢你的站点主题，但是永久之后发现，整体黑暗暗的。有点显脏。。能否通过配置切换整体的色彩配置颜色。。

例如title和code区域的黑色背景，换成其他偏清爽些的色彩？

谢谢。。

**Comment by Gaohaoyang** [comment]
嗯，可以考虑做这个功能。当然如果你懂一点点CSS的话，完全可以自己去修改

**Comment by waruqi** [comment]
恩，现在已经效果挺好了，我一直在用，最近整成多语言版本，稍微费了点时间，要是主题能原生支持多语言就好了。。: )

**Comment by Gaohaoyang** [comment]
@waruqi 我看到你的disqus留言了，已经添加了链接，你改版的多语言也很赞！

**Comment by waruqi** [comment]
谢谢。。但是还是有些问题，不太好处理，例如：tags的多语言过滤，对jekyll还不是特别了解，改起来有点麻烦。。

**Comment by waruqi** [comment]
tags过滤 我搞定了。。谢谢哈。。: )

**Comment by Gaohaoyang** [comment]
嗯……tag只是post文章的一个属性字段，我觉得你可以自定义文章头部的字段名称，比如英文的叫tag_en，然后分开展示。我觉得这是一个可行的办法。

**Comment by waruqi** [comment]
恩 谢谢，我现在是通过过滤url是否包含 `/cn/` 来处理的，目前看下来效果也还行。。

        {% capture tags %}
          {% for tag in site.tags %}
           {% if tag[1].size > 0 %}
           {% assign post_first = tag[1][0] %}
           {% unless post_first.url contains '/cn/' %}
            {{ tag[0] }}
           {% endunless %}
           {% endif %}
          {% endfor %}
        {% endcapture %}

**Comment by Gaohaoyang** [comment]
nice job!
