### ISSUE TITLE
修改博文时间导致无法显示到主页的问题

### ISSUE THREAD

**Issue by jonydev** [Gaohaoyang/gaohaoyang.github.io#34]
浩阳，你好，感谢你的模板，非常棒。有一个小bug，请修复一下：
post文件夹下，以当天时间命名文件明，在md文件中，date设置为当前时间，直接用jekyll serve在本地显示，这篇文字显示不出来。我如果把时间往前改，例如改到昨天，就可以正常显示了，不太清楚原因，请帮忙分析一下，谢谢。另外我是添加的第一篇文章，不知道跟这个有没有关系。

**Comment by ifreyr** [comment]
你在时间最后加上时区，格式如2016-12-11 10:43:34 +0800

**Comment by jonydev** [comment]
thank you
