### ISSUE TITLE
当我输入jekyll s的时候，出现了问题

### ISSUE THREAD

**Issue by ChenPHPER** [Gaohaoyang/gaohaoyang.github.io#41]
Configuration file: none
            Source: /Users/chenyanhua
       Destination: /Users/chenyanhua/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
             Error: could not read file /Users/chenyanhua/Documents/EZLippi.github.io/_posts/2014-11-01-android-push.md: (<unknown>): could not find expected ':' while scanning a simple key at line 7 column 1
             Error: could not read file /Users/chenyanhua/Documents/EZLippi.github.io/_posts/2014-11-01-java-nio.md: (<unknown>): could not find expected ':' while scanning a simple key at line 6 column 1
jekyll 3.2.1 | Error:  Operation not supported on socket @ rb_sysopen - /Users/chenyanhua/Library/Application Support/Google/Chrome/App Shim Socket

**Comment by Gaohaoyang** [comment]
报错提示很明显了

```
could not find expected ':' while scanning a simple key at line 7 column 1
```

目测是你的第七行的分号后面少了一个空格
