### ISSUE TITLE
jekyll运行服务的时候出现问题？

### ISSUE THREAD

**Issue by Jandaes** [Gaohaoyang/gaohaoyang.github.io#42]
运行服务的时候出现这个、
Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!

**Comment by Gaohaoyang** [comment]
参考这里
https://gaohaoyang.github.io/2016/03/12/jekyll-theme-version-2.0/#jekyll-paginate-
