### ISSUE TITLE
建议：优化加载速度

### ISSUE THREAD

**Issue by fan19900404** [Gaohaoyang/gaohaoyang.github.io#44]
# 建议使用CDN服务加速第三方组件
## 原因

总所周知，github在国内方法是比较慢的，架构在github上的博客那自然也是很慢的。而框架中使用fontawesome字体，那速度慢的不是一点半点。
## 解决办法

使用其它免费的CDN服务来解决这一个问题，加载速度可以提高很多。比如使用http://www.bootcdn.cn/的上的fontawesome，即`//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css`

**Comment by Gaohaoyang** [comment]
嗯，已经做了修改，谢谢。
