### ISSUE TITLE
……为什么我用markdown语法在本地编辑器写完，传上去就乱序了，格式也不正确，你对语法修改了么

### ISSUE THREAD

**Issue by JiaoHongwei** [Gaohaoyang/gaohaoyang.github.io#45]

**Comment by Gaohaoyang** [comment]
没有做任何修改，把你的git地址发出来看看。

**Comment by honghaoli** [comment]
我也遇到同样的问题， 经过检查后， 发现github-page 默认的插件组不一样， 所以local端看起来和server端markdown格式语法都不一样。

默认的Gemfile是这样的：

# frozen_string_literal: true
source "https://rubygems.org"
ruby RUBY_VERSION

# gem "rails"
# gem "rspec"
# gem "jekyll-paginate"


# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
# gem "jekyll", "3.3.1"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
# gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
end

重点是后面的
gem "github-pages", group: : jekyll_plugins

如果uncomment这行

则local显示的和github上面的完全一样，格式很乱，俩都于你设置的markdown显示不一样。



所以不太清楚你用到的Gemfile是什么格式。
