### ISSUE TITLE
Paginate功能下一页不能正常跳转

### ISSUE THREAD

**Issue by tigerliuwu** [Gaohaoyang/gaohaoyang.github.io#47]
首页里，点击paginate中的下一页，得到的url为:<http://gaohaoyang.github.io/page2/>，事实上应该为<https://gaohaoyang.github.io/page2/>。通过jekyll s在本地运行时，该问题不存在。

**Comment by Gaohaoyang** [comment]
这个应该是你的配置问题

**Comment by Gaohaoyang** [comment]
现在我的线上的是好的。

**Comment by tigerliuwu** [comment]
嗯，确实好用了。我这边什么都没修改，现在在github上面也是好用的了，我猜想是github page服务器造成的。
