### ISSUE TITLE
关于新版的建议-风格&目录

### ISSUE THREAD

**Issue by brianway** [Gaohaoyang/gaohaoyang.github.io#5]
看到你的readme更新了，就说下我的建议吧。

1.希望整体主题风格不变，比较喜欢这种**纯色**的暗基调，简单沉稳；不喜欢极客纯白，感觉空空的。

2.希望能保留和优化“目录”功能，就是在博文中添加下面代码后出现的那个目录

```
* content
{:toc}
```

特别喜欢这个功能，可以完善的地方有：

- 扩展到其他页面，而不只博文页面。比如个人简介、项目介绍、友链等页面都加入目录,，是否开启目录由**用户自选**。
- 动态跟踪当前所在段落。可以参考[SegmentFault社区](http://segmentfault.com/),比如我的[这篇文章](http://segmentfault.com/a/1190000004157393)，下拉文章，网页右边目录会标记出当前所处位置

3.其他的比如**搜索**、**标签**等功能你在readme里已经提到了，不赘述。

**Comment by Gaohaoyang** [comment]
嗯，很高心看到你的建议！记下了，谢谢！！！

看了你的 [hadoop完全分布式模式的安装和配置步骤](http://segmentfault.com/a/1190000004157393) 文章的目录样式，是的，这也是我正想要的。

目录扩展到其他页面是个好想法！

**Comment by Gaohaoyang** [comment]
博客主题已更新，请看README
