### ISSUE TITLE
在_post下建立blog遇到的有关时间的问题

### ISSUE THREAD

**Issue by NaughtyTiger** [Gaohaoyang/gaohaoyang.github.io#52]
我试图在_post下新建markdown文件时，发现按照当前时间新建（例如，开头的时间写 "date: 2016-12-20 16:30:02"）markdown文件，然后执行jekyll s的话，生成的网站上无法显示这篇文章，需要把这个时间至少往前8个小时才能显示。所以是不是哪里调用了标准时间而不是本地时间导致了这个问题. 所以网站的当前时间是哪里获取的，能不能设置时区呢？

**Comment by Gaohaoyang** [comment]
你应该添加时区

https://jekyllrb.com/docs/frontmatter/#predefined-variables-for-posts <https://jekyllrb.com/docs/frontmatter/#predefined-variables-for-posts>

`YYYY-MM-DD HH:MM:SS +/-TTTT`
