### ISSUE TITLE
求助：配置多说shortname，不能正常使用

### ISSUE THREAD

**Issue by chensirup** [Gaohaoyang/gaohaoyang.github.io#54]
您好，fork了您的博客模版，谢谢您的用心，非常好用，只是关于多说评论设置时有些问题，求助。

按要求在_config.yml文件中配置了多说的shortname，有显示**Comments**，但评论没有出来，还请指教，万分感谢。

**Comment by Gaohaoyang** [comment]
这个不应该啊

**Comment by jourdon** [comment]
多说都要倒闭了，可以换其它的评论插件了

**Comment by Jandaes** [comment]
@jourdon  那你是用的哪个插件？畅言么

**Comment by jourdon** [comment]
@Jandaes 嗯。多说没了。也没有别的好用的。先弄个放上呗

**Comment by Jandaes** [comment]
@jourdon  畅言是搜狐旗下产品、好像要网站备案才能用吧

**Comment by jourdon** [comment]
@Jandaes 是啊。不过我是真不喜欢畅言的。。乱七八糟的东西太多了。

**Comment by Jandaes** [comment]
@jourdon 没备案你是怎么使用的？ 多说界面看着舒服，且与这主题很搭

**Comment by Gaohaoyang** [comment]
我现在使用了disqus，不过需要翻墙貌似也不是最优方案

但是现在貌似开始流行直接使用 github issue 当做评论了

https://imsun.net/posts/gitment-introduction/

@jourdon @Jandaes

**Comment by Jandaes** [comment]
@Gaohaoyang  评论是直接引用issue 的吗？issue直接在博客文章里面显示啊 :+1:

**Comment by Gaohaoyang** [comment]
@Jandaes 是的，我还没有深入研究，但是看起来很棒

**Comment by Jandaes** [comment]
@Gaohaoyang  谢谢、如何集成呢？不知道我们这主题会不会有呢 :smiley:

**Comment by Gaohaoyang** [comment]
你可以看下
https://imsun.net/posts/gitment-introduction/

有时间我会研究一下的

**Comment by jourdon** [comment]
@Jandaes 我的域名有备案，所以没有问题 ，Gitment这个界面看着就比较舒服，简单。

**Comment by Jandaes** [comment]
@jourdon @Gaohaoyang  谢谢、这个的确很好，清爽！我常识照着博文做下、希望能实现 :point_up:

**Comment by AndyTsangChun** [comment]
想問一下用disqus 只需要在_config.yml 的disqus_shortname設定嗎？
因為我設定了還是load 不到，只有這句"We were unable to load Disqus. If you are a moderator please see our troubleshooting guide."
