### ISSUE TITLE
首页显示全文太多，能否给出缩略

### ISSUE THREAD

**Issue by ifreyr** [Gaohaoyang/gaohaoyang.github.io#55]
目前首页会完整的显示最近的文章，后面的文章也显示的很多，能否调整至给出文章内容的前10行或者正文添加简介标签，主页只显示简介。

![default](https://cloud.githubusercontent.com/assets/11648367/22743508/57b6de5a-ee55-11e6-9936-eeb06d358565.png)

**Comment by Gaohaoyang** [comment]
https://github.com/Gaohaoyang/gaohaoyang.github.io/blob/master/README-zh-cn.md#4-%E5%86%99%E6%96%87%E7%AB%A0

> 文章中存在的4次换行为摘要分割符，换行前的内容会以摘要的形式显示在主页Home上，进入文章页不影响。
>
> 换行符的设置见配置文件_config.yml的 excerpt，如下：

```
# excerpt
excerpt_separator: "\n\n\n\n"
```

**Comment by pkxpp** [comment]
终于解决这个问题了~ 太隐蔽了
