### ISSUE TITLE
请问如何修改markdown的代码显示样式

### ISSUE THREAD

**Issue by VincentFF** [Gaohaoyang/gaohaoyang.github.io#60]
非常感谢博主分享模板。

我不太喜欢代码显示的那个深色主题，感觉跟背景不太搭
想更改为类似github的浅色样式，没有找到如何修改，请教在哪里进行修改。

**Comment by Gaohaoyang** [comment]
替换这个文件 `_sass/_syntax-highlighting.scss`

**Comment by VincentFF** [comment]
@Gaohaoyang 好的，谢谢
