### ISSUE TITLE
css 赋值错误(word-break: break-word;)？

### ISSUE THREAD

**Issue by brianway** [Gaohaoyang/gaohaoyang.github.io#64]
在你的源代码 `_sass/_page.scss`第 113 行

https://github.com/Gaohaoyang/gaohaoyang.github.io/blob/master/_sass/_page.scss#L113

```css
word-break: break-word;
```

我查了下，只有下面两种写法，没有上面的写法，即 `word-break` 没有 `break-word`的值

```
word-wrap:break-word;
word-break:break-all;
```

> reference: http://www.w3school.com.cn/cssref/pr_word-break.asp

**Comment by Gaohaoyang** [comment]
感谢指出，如果你有兴趣的话，你可以提一个 pull request 我来合并

或者我周末改一下
@brianway

**Comment by brianway** [comment]
感谢回复，由你来改吧，方便一些...重点看我另一个issue #65 ，主要想让你解决这个问题。

**Comment by Gaohaoyang** [comment]
好的
@brianway
