### ISSUE TITLE
既然能提建议，我就也提一些吧

### ISSUE THREAD

**Issue by zhaodedong** [Gaohaoyang/gaohaoyang.github.io#7]
首先表示不怎么懂前端，我是后端的数据研发，一直用你这个blog模板，其实最近有打算买太虚拟机自己用Python搞一套，嫌太麻烦，既然你要更新，我就看看你更新的模板，然后继续用你的了。嘿嘿。
关于现在这个模板，简洁大方，这也是我当初从那么多中选中这个模板的原因，很感谢。
小建议，感觉合适麻烦采纳，我不太懂，不知道实现难度，而且自己比较懒，不想动手，所以把我的所有想法都说一下，请见谅。
1.首先是标签，标签云你感觉怎么样，就是那种看着会动的，你可以也弄成灰色的会动的标签云，是不是好玩一些？
2.文章archive，按年归档一下？我看见一个一哥们已经搞了。
3.代码高亮？我有一点强迫症，咱们这个模板的代码高亮只有用jekyll的才好看，用标准md的```貌似没什么效果，这个是代码设置的原因，还是什么？我用别的博客模板解析的markdown的代码高亮比较正常，咱们这个貌似最后只能用jekyll才行。我想要一个通用的，这样，在csdn和git上的文章互相copy也不用再手动改了？
4.目录，建是不是能让目录随着界面向下移动？现在是固定死到界面顶部的
5.一步到位地帮我们这帮前端白痴们设置几个界面？比如issues里面那个哥们，他的主页我感觉挺不错的，加了不少功能，你应该感觉比较简单没必要加，嘿嘿，我厚着脸皮希望能加几个常用功能的界面，内容我们自己填，这样我就不再费时折腾了（虽说也能折腾出来，我比较早的时候用你的模板，自己折腾添加了上一篇下一篇按钮，就是比较耗时间）。
6.布局，还有一个，我不知道是否合适，所以放在最后。就是样式布局，比如说现在很多主流的blog的用户信息以及网页链接是在左侧，这样可以上传图片什么的，比如java的那个开元blog solo，https://github.com/b3log/solo
我有打算过用这个，自己在本地跑过。你感觉这种怎样？有没有必要开一个分支？

**Comment by zhaodedong** [comment]
另外，相当期待早点搞啊，祝楼主早点完成论文，早点写一个新模板出来。来北京我请你吃饭。

**Comment by Gaohaoyang** [comment]
好，都记下了，非常感谢你

**Comment by Gaohaoyang** [comment]
博客主题已更新，请看README
