### ISSUE TITLE
 Category关键词有空格导致超链接问题？

### ISSUE THREAD

**Issue by YoujieXia** [Gaohaoyang/gaohaoyang.github.io#70]
- 某Category命名为形如 `“A B”` 形式，中间有空格：
    - Home界面中Category的超链接没有问题，可以正常对应到正确位置；
    - 但在Categories页面中，点击 `“A B”` 无法对应到当页正确位置，无空格则没问题。
    - 请见[问题示例](https://youjiexia.github.io/category/)，倒数几个类别名称均失效。

------
PS: 我看过 `index.html` 和 `/_includes/category.html`里面对应的代码，可是本人技术比较渣，改了几次没改对，求助。。。

**Comment by TangMingliang95** [comment]
我觉得这可能和 `href` 这个属性有关，
有两个解决方案：
1. 不使用空格
2. 用 `href="/category/#Computer Science"` 代替 `href="#Computer Science"` ，缺点是每次都要重新访问
```html
                <ul id="content-side" class="content-ul">
                    {% for category in site.categories%}
                        <li>
                            <a data-scroll href="#{{ category | first }}">
                                {{ category | first }} ({{ category | last | size }})
                            </a>
                        </li>
                    {% endfor %}
                </ul>
```
把 `page/1category.html` 里的这句话 `<a data-scroll href="#{{ category | first }}">` 修改一下

**Comment by YoujieXia** [comment]
@TangMingliang95 谢谢你的回复。

- 第一个方案不使用空格我有考虑过，但是目前想保留空格。
- 第二个方案我试了下，修改为`href="/category/#{{ category | first }}`后，所有的超链接均失效。

**Comment by TangMingliang95** [comment]
@YoujieXia 我自己测试不用做任何修改，可以正常跳转。你出问题的原因是没有及时更新模板。

事实上， @Gaohaoyang 在二月的提交[update scroll smooth](https://github.com/Gaohaoyang/gaohaoyang.github.io/commit/256b8c4df59f65e1e6f8951c9353484d0ba392e3)中已经把滚动方法改为使用data-scroll，而你还是使用旧版本的"scroll" class，所以出了问题。

更新相关文件应该可以解决你的问题。

**Comment by YoujieXia** [comment]
@TangMingliang95 非常感谢！才看到，根据update scroll smooth的记录已经修复了此问题。

@Gaohaoyang 请close该issue，谢谢！
