### ISSUE TITLE
jekyll-paginate 报错

### ISSUE THREAD

**Issue by 6xian** [Gaohaoyang/gaohaoyang.github.io#73]
感谢您的分享。有个问题一直解决不了，还请帮忙。
jekyll serve 启动站点的时候，一直抱 缺少 jekyll-paginate 的错误，我 gem install  jekyll-paginate 后也还是一直报错，能确认确实装上了这个包(
jekyll-paginate (1.1.0))

  Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
jekyll 3.5.0 | Error:  jekyll-paginate

**Comment by 6xian** [comment]
这里有解决的办法
https://github.com/jekyll/jekyll/issues/4124

# Gemfile

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-paginate"
end

**Comment by Herwt-liyj** [comment]
jekyll 3.8.6, resolve this error
one step:
#Gemfile  
group :jekyll_plugins do
gem "jekyll-feed", "~> 0.6"
gem "jekyll-paginate"
end
two step:
# _config.yml  end new add
gem "jekyll-paginate"
