### ISSUE TITLE
关于留言-使用gitment-的修改案

### ISSUE THREAD

**Issue by ericsimith** [Gaohaoyang/gaohaoyang.github.io#84]
Gitment：使用 GitHub Issues 搭建评论系统
https://imsun.net/posts/gitment-introduction/

全部回归到一个网站上，我觉得会更好

**Comment by tomoya92** [comment]
今天我配了一下，不怎么好用，每个博客都要点一下初始化，虽然有自动化脚本，不过感觉不够优雅
