### ISSUE TITLE
如何去掉navigation bar里面不想要的模块

### ISSUE THREAD

**Issue by bchen4** [Gaohaoyang/gaohaoyang.github.io#95]
感谢做出这个模板
尝试注释掉_site/index.html 相关的两个<li> 但是刷新后 Collection 和 Demo 依然存在。
可以在readme里面写写如何改这个么。。。
html小白已经折腾了半天了orz。。。

感谢！！！

**Comment by TangMingliang95** [comment]
@bchen4 把 page 文件夹下对应的页面删掉即可。

**Comment by bchen4** [comment]
感谢！！ @TangMingliang95
